  0%|          | 0/267 [00:00<?, ?batch/s]/databricks/python/lib/python3.11/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
100%|██████████| 267/267 [02:57<00:00,  1.50batch/s, loss=8.87e+3]
100%|██████████| 3/3 [00:19<00:00,  6.59s/batch, loss=80.4]
Epoch 0/50 | Train Loss: 33.21005954813868 | Val Loss: 26.81597328186035
100%|██████████| 267/267 [02:53<00:00,  1.54batch/s, loss=6.7e+3] 
100%|██████████| 3/3 [00:19<00:00,  6.45s/batch, loss=69]  
Epoch 1/50 | Train Loss: 25.103536684414866 | Val Loss: 23.015370051066082
 55%|█████▍    | 146/267 [01:35<01:09,  1.75batch/s, loss=3.29e+3]Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fbe1884aca0>
Traceback (most recent call last):
  File "/databricks/python/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1479, in __del__
    self._shutdown_workers()
  File "/databricks/python/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1462, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/process.py", line 165, in is_alive
    returncode = self._popen.poll()
                 ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt:
 55%|█████▍    | 146/267 [01:44<01:26,  1.40batch/s, loss=3.29e+3]

KeyboardInterrupt
