  0%|          | 0/267 [00:00<?, ?batch/s]/databricks/python/lib/python3.11/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
100%|██████████| 267/267 [02:54<00:00,  1.53batch/s, loss=1.16e+4]
100%|██████████| 3/3 [00:19<00:00,  6.59s/batch, loss=119] 
Epoch 0/50 | Train Loss: 43.41487007283986 | Val Loss: 39.58047739664713
100%|██████████| 267/267 [02:51<00:00,  1.55batch/s, loss=1.04e+4]
100%|██████████| 3/3 [00:18<00:00,  6.26s/batch, loss=114] 
Epoch 1/50 | Train Loss: 38.94043993146232 | Val Loss: 37.844932556152344
  4%|▍         | 12/267 [00:17<03:00,  1.41batch/s, loss=462]Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f064ca7ad40>
Traceback (most recent call last):
  File "/databricks/python/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1479, in __del__
    self._shutdown_workers()
  File "/databricks/python/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1462, in _shutdown_workers
    if w.is_alive():
       ^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/process.py", line 165, in is_alive
    returncode = self._popen.poll()
                 ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt:
  4%|▍         | 12/267 [00:26<09:22,  2.21s/batch, loss=462]

KeyboardInterrupt

  0%|          | 0/267 [00:00<?, ?batch/s]/databricks/python/lib/python3.11/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
  0%|          | 1/267 [00:21<1:35:11, 21.47s/batch, loss=4.94]
